-- begin SPEEDYPIZZA_DISH_TYPES
create unique index IDX_SPEEDYPIZZA_DISH_TYPES_UNIQ_DISH_TYPE on SPEEDYPIZZA_DISH_TYPES (DISH_TYPE) ^
-- end SPEEDYPIZZA_DISH_TYPES

-- begin SPEEDYPIZZA_DISHES
alter table SPEEDYPIZZA_DISHES add constraint FK_SPEEDYPIZZA_DISHES_ON_DISH_TYPE foreign key (DISH_TYPE_ID) references SPEEDYPIZZA_DISH_TYPES(ID)^
create index IDX_SPEEDYPIZZA_DISHES_ON_DISH_TYPE on SPEEDYPIZZA_DISHES (DISH_TYPE_ID)^
-- end SPEEDYPIZZA_DISHES

-- begin SPEEDYPIZZA_DISHES_INGREDIENTS_LINK
alter table SPEEDYPIZZA_DISHES_INGREDIENTS_LINK add constraint FK_DISING_ON_DISHES foreign key (DISHES_ID) references SPEEDYPIZZA_DISHES(ID)^
alter table SPEEDYPIZZA_DISHES_INGREDIENTS_LINK add constraint FK_DISING_ON_INGREDIENTS foreign key (INGREDIENTS_ID) references SPEEDYPIZZA_INGREDIENTS(ID)^
-- end SPEEDYPIZZA_DISHES_INGREDIENTS_LINK
-- begin SPEEDYPIZZA_INGREDIENTS
alter table SPEEDYPIZZA_INGREDIENTS add constraint FK_SPEEDYPIZZA_INGREDIENTS_ON_DISH_TYPES foreign key (DISH_TYPES_ID) references SPEEDYPIZZA_DISH_TYPES(ID)^
create index IDX_SPEEDYPIZZA_INGREDIENTS_ON_DISH_TYPES on SPEEDYPIZZA_INGREDIENTS (DISH_TYPES_ID)^
-- end SPEEDYPIZZA_INGREDIENTS
-- begin SPEEDYPIZZA_ORDER
alter table SPEEDYPIZZA_ORDER add constraint FK_SPEEDYPIZZA_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SPEEDYPIZZA_CUSTOMER(ID)^
create index IDX_SPEEDYPIZZA_ORDER_ON_CUSTOMER on SPEEDYPIZZA_ORDER (CUSTOMER_ID)^
-- end SPEEDYPIZZA_ORDER
-- begin SPEEDYPIZZA_ORDER_DISHES_LINK
alter table SPEEDYPIZZA_ORDER_DISHES_LINK add constraint FK_ORDDIS_ON_DISHES foreign key (DISHES_ID) references SPEEDYPIZZA_DISHES(ID)^
alter table SPEEDYPIZZA_ORDER_DISHES_LINK add constraint FK_ORDDIS_ON_ORDER foreign key (ORDER_ID) references SPEEDYPIZZA_ORDER(ID)^
-- end SPEEDYPIZZA_ORDER_DISHES_LINK
