alter table SPEEDYPIZZA_CUSTOMER alter column CUBA_USER_ID rename to CUBA_USER_ID__U55141 ^
drop index IDX_SPEEDYPIZZA_CUSTOMER_ON_CUBA_USER ;
alter table SPEEDYPIZZA_CUSTOMER drop constraint FK_SPEEDYPIZZA_CUSTOMER_ON_CUBA_USER ;
