alter table SPEEDYPIZZA_INGREDIENTS alter column DISHES_ID rename to DISHES_ID__U44235 ^
drop index IDX_SPEEDYPIZZA_INGREDIENTS_ON_DISHES ;
alter table SPEEDYPIZZA_INGREDIENTS drop constraint FK_SPEEDYPIZZA_INGREDIENTS_ON_DISHES ;
