alter table SPEEDYPIZZA_CUSTOMER add constraint FK_SPEEDYPIZZA_CUSTOMER_ON_CUBA_USER foreign key (CUBA_USER_ID) references SEC_USER(ID);
create index IDX_SPEEDYPIZZA_CUSTOMER_ON_CUBA_USER on SPEEDYPIZZA_CUSTOMER (CUBA_USER_ID);
