alter table SPEEDYPIZZA_ORDER add constraint FK_SPEEDYPIZZA_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SPEEDYPIZZA_CUSTOMER(ID);
create index IDX_SPEEDYPIZZA_ORDER_ON_CUSTOMER on SPEEDYPIZZA_ORDER (CUSTOMER_ID);
