alter table SPEEDYPIZZA_CUSTOMER alter column CUSTOMER_CURRENT_DISCOUNT rename to CUSTOMER_CURRENT_DISCOUNT__U44051 ^
alter table SPEEDYPIZZA_CUSTOMER add column CUSTOMER_CURRENT_DISCOUNT decimal(19, 2) ;
